/** Supported Cosmos Hub governance proposal types */
export type ProposalType = 'parameterChange' | 'communityPoolSpend' | 'softwareUpgrade' | 'text' | 'ibcClientUpdate'

/** Vote option matching Cosmos Hub governance options */
export type VoteOption = 'yes' | 'no' | 'abstain' | 'noWithVeto'

/** Proposal difficulty rating affecting NPC vote distribution */
export type Difficulty = 'straightforward' | 'contested' | 'divisive'

/** A governance proposal generated by Claude */
export interface Proposal {
  id: string
  type: ProposalType
  title: string
  summary: string
  forArguments: string[]
  againstArguments: string[]
  difficulty: Difficulty
  createdAt: number
  closesAt: number
  status: 'active' | 'closed'
  winningOption?: VoteOption
  narration?: string
}

/** A player's vote on a proposal */
export interface Vote {
  proposalId: string
  playerAddress: string
  option: VoteOption
  stakeAmount: number
  reward: number
  castAt: number
}

/** Vote tally showing ATOM staked per option */
export interface Tally {
  yes: number
  no: number
  abstain: number
  noWithVeto: number
}

/** A player in the governance simulation */
export interface Player {
  address: string
  balance: number
  totalEarned: number
  totalVotes: number
  winRate: number
}

/** An NPC voter for simulated chamber activity */
export interface NpcVoter {
  address: string
  balance: number
  preferredOption: VoteOption
  voteTime: number
}

/** An NPC vote cast during the voting window */
export interface NpcVote {
  voterAddress: string
  option: VoteOption
  stakeAmount: number
}

/** Global game state managed by Zustand */
export interface GameStore {
  player: Player | null
  proposals: Proposal[]
  votes: Vote[]
  activeProposalId: string | null
  leaderboard: Player[]
  setPlayer: (player: Player) => void
  addProposal: (proposal: Proposal) => void
  castVote: (vote: Vote) => void
  updateBalance: (amount: number) => void
  setActiveProposalId: (id: string | null) => void
  updateProposal: (id: string, updates: Partial<Proposal>) => void
  addLeaderboardEntry: (player: Player) => void
  updateLeaderboard: (player: Player) => void
}
